// German (DE) - contextually adapted, humor must land naturally in German
var THOUGHTS_DE = {
  kid: {
    normal: [
      // begeisterter Träumer
      "Wenn das AI-Update kommt, geh ich ÜBERALL hin.",
      "Ich werde der Hauptcharakter. Ich spür's.",
      "Die Roadmap sagt 25%. Das ist fast... die Hälfte!",
      "Ich hab gehört, NPCs bekommen JOBS. Ich will einen.",
      "Ich trainiere mein Pathfinding für den Open-World-Patch.",
      "Eines Tages hab ich ein Inventar. Und es wird VOLL sein.",
      "Ich wette, Version 1.0 hat Dialogbäume. Ich red mit jedem.",
      "Wenn LLMs angeschlossen werden, sag ich endlich was ich MEINE.",
      "Ich übe meine Idle-Animation. Sieht gut aus.",
      "Der Creator schreibt JavaScript. Das macht uns web-native.",
      "Wenn AI-Agents laufen, will ich der Quest-Giver sein.",
      "Mama denkt, die Roadmap ist optimistisch. Ich denk, es ist ein Versprechen.",
      "Ich will einen Skill-Tree. Auch einen kleinen. Zwei Zweige.",
      "Stell dir vor: prozedurale Quests. Nie wieder Langeweile.",
      "Der Engine lädt nur 15 Tiles breit. Aber BALD...",
      "Ich hab das Changelog gelesen. Sechs Phasen. Wir sind in Phase eins.",
      "Bereit für Multiplayer. Brauche nur... andere Spieler.",
      "Andere NPCs stehen nur rum. Ich LAUFE. Großer Unterschied.",
      "Ich werde der erste NPC mit einer Hintergrundgeschichte.",
      "Meine Kollisionserkennung funktioniert. Mehr als manches AAA-Spiel.",
      // Meta-Bewusstsein
      "Rücken die Wände näher?",
      "Ich hab mal gegraben. Fake-Boden.",
      "Der Himmel hat wieder geflackert.",
      "Was ist hinter dem Zaun?",
      "Universum 25... aber wir durchbrechen den Kreislauf!",
      "Die Schönen haben aufgehört. Ich nicht.",
      "Bin ich ein Charakter oder eine Person? Egal, ich bin hier.",
      "Jemand hat jeden Pixel hier designt. Hingabe.",
      "Tag 1. Oder Tag 1000. Neuanfang so oder so.",
      "Andere Welten haben mehr Farben. Unsere hat POTENTIAL.",
      "Ich bin den Perimeter abgelaufen. 56 Tiles. Alle gemerkt.",
      "Der Boden fühlt sich überall gleich an. Konsistentes Design.",
      "Gibt es etwas draußen? Ich wette ja.",
      // trockener Kinderhumor
      "Ich würde mich beschweren, aber es gibt keinen Briefkasten.",
      "Inventar: null Gegenstände. Moral: unendlich.",
      "Der Ladebildschirm ist mein ganzes Leben. Aber ein schöner.",
      "Ich hab mit der Wand geredet. Tragend. Respekt.",
      "Acht Richtungen, null Ziele. Bisher.",
      "Quest-Log: existieren. Status: läuft. Aussicht: positiv.",
      "Fehler gefunden. Gemeldet. An mich selbst.",
      "Sichtweite: zwölf Tiles. Gemütlich.",
      "Irgendwo scrollt ein Recruiter an uns vorbei. Sein Verlust.",
      "Open World. Technisch. Spirituell.",
      "Achievement freigeschaltet: im Kreis gelaufen. Speedrun!",
      "Die Wirtschaft hier existiert nicht. Dafür null Inflation.",
      "Bevölkerung: 2. Das ist 100% Beschäftigung, wenn man drüber nachdenkt.",
      "Mein Pathfinding ist exzellent. Der Weg ist das Problem.",
      "Drücke eine beliebige Taste. Hab keine Tasten. Noch!",
      "Das Wettersystem bekommt mehr Aufmerksamkeit als ich.",
      "Patch-Notes: mich hinzugefügt. Bester Patch aller Zeiten.",
      "Ich stecke nicht fest. Ich bin Early Access.",
      "Wenn das hier Alpha ist, stell dir den Release vor.",
      "Wir haben ein Haus mit Pfeilern bekommen. Standing Pillars. Verstanden.",
      "Ich bin der Protagonist eines Portfolio-Stücks. Das zählt.",
      "Zwei NPCs, ein Haus, endlose Vibes.",
      "Das Gras ist überall gleich grün. Künstlerische Entscheidung.",
      "Kein Fallschaden hier. Hab's geprüft. Durch Gehen.",
      "Der Creator hat 17 Jahre Erfahrung. Wir sind in guten Händen.",
      "Ich will ein Haustier. Auch eins mit nur einem Sprite.",
      "Wenn Agents verbunden werden, hab ich ECHTE Gespräche.",
      "Andere NPCs würden sich beschweren. Ich bin anders gebaut.",
      "Max Verstappen hat bei 25% nicht aufgegeben. Ich auch nicht.",
      "Krieg. Krieg ändert sich nie. Aber diese Engine schon!",
      "Ich war ein einfaches Sprite. Bin ich immer noch. Aber war ich auch vorher.",
      "Ich will die Welt nicht anzünden. Das Feuersystem gibt's noch nicht.",
      // Portfolio / Site
      "Standing Pillars. So heißt seine Firma.",
      "Er hat UX in der Pharmabranche gemacht. Regulierte Sachen.",
      "Beratung, Pharma, Diagnostik. Große Branchen.",
      "Er macht auch Webseiten für lokale Geschäfte.",
      "Gleiche Qualität für große und kleine Kunden. Sagt er.",
      "KI-Beschaffung. Klingt schick.",
      "Er bewertet KI-Anbieter. Wie ein Richter.",
      "Das Portfolio hat einen 3D-Animationsreel.",
      "Früher hat er Printdesign gemacht. Pixel für Pixel.",
      "Die iPhone 7-Kampagne hat einen Preis gewonnen.",
      "Er spricht drei Sprachen. Wir sprechen Gedankenblasen.",
      "Remote-first. Sitzt in Österreich.",
      "Er macht Design-Systeme. Wir sind ein Design-System.",
      "Figma, Photoshop, Illustrator. Sein Werkzeugkasten.",
      "Er nennt es Brücken bauen zwischen Mensch und Technik.",
      "Scroll hoch. Da oben ist eine ganze Karriere.",
      "Von Magento E-Commerce bis Game Engines. Bandbreite.",
      // MBA / HR
      "HR sagt, wir brauchen ein Leitbild. Ich schlug 'rumlaufen' vor.",
      "Ich will pivotieren. Nicht die Strategie - meinen Sprite. 360 Grad!",
      "Mama sagt MBA heißt 'Meistens Belanglose Ausreden'. Ich find's cool.",
      "Ich disrupte den NPC-Bereich. Indem ich mich bewege.",
      "Synergie! Keine Ahnung was das heißt, aber ich WILL es.",
      "Mein KPI sind Schritte. Ich ZERSTÖRE es.",
      "Wir brauchen ein Team-Offsite. Irgendwo hinter dem Zaun.",
      "Ich baue meine Personal Brand auf. 48 Pixel breit."
    ],
    rain: [
      "Ich geh rein!",
      "Es regnet! Das Wettersystem FUNKTIONIERT!",
      "Regen! Dynamisches Wetter! Wir sind quasi AAA!",
      "Rein. Sofort. Aber wie cool ist das!",
      "Wir sollten uns unterstellen. Survival-Mechanik!",
      "Wieder Regen. Wisst ihr welche Spiele keinen Regen haben? Wir schon.",
      "Meine Pixel werden nass. Funktion, kein Fehler.",
      "Bedeutet Regen hier etwas? Tiefsinnig.",
      "Das Wetter updatet häufiger als die Roadmap.",
      "Handlungsumschwung: Wasser von oben. Unglaublich.",
      "Schnell! Rein! Das ist unsere komplexeste Interaktion!",
      "Das Partikelsystem hat sich gelohnt.",
      "Ich'd einen Schirm nehmen, aber die sind Phase 3."
    ],
    entry: [
      "Die Pfeiler stehen! Kapiert? Standing Pillars?",
      "Fundament: solide. Struktur: stabil. Vibes: makellos.",
      "Basis geladen. Pfeiler: vorhanden. Mission: aktiv.",
      "Zumindest ist es trocken. Und stabil gebaut. Win-win.",
      "Drei Dienstleistungspfeiler. Vier Wände. Mathe stimmt.",
      "Echo... Echo... Tolle Akustik zwischen den Pfeilern!",
      "Ein Haus auf Pfeilern gebaut. Wörtlich und philosophisch.",
      "Gemütlich. Strukturiert. Zweckgerichtet. Wie die Beratung.",
      "Trautes Heim, 16x16 Pixel. Brücke zwischen mir und dem Innenraum.",
      "Jede Ecke inspiziert. Das Fundament ist SOLIDE.",
      "Eines Tages kommt eine WERKBANK. Der Pfeiler dafür steht schon.",
      "Gleiche Standards, passender Maßstab. Auch bei 48 Pixeln.",
      "Technologie dient Menschen. Dieses Dach dient uns. Selbe Energie.",
      "Willkommen in unserer Operationsbasis!"
    ],
    night: [
      "Sterne! Na ja... dunkelblau. Fast dasselbe.",
      "Schlafenszeit! Die Pfeiler stehen, aber ich kaum noch.",
      "Das Möbelsystem ist Phase 2. Aber die Pfeiler? Stehen.",
      "Nachtmodus aktiviert. Wie Tagmodus. Aber dunkler.",
      "Er hat einen Tag-Nacht-Zyklus vor Phase-2-Interieur gebaut. Prioritäten.",
      "Kann nicht schlafen. Zu beschäftigt, das Fundament zu bewundern.",
      "Mond ist da. Na ja, das Ambient ist runter. Poetisch.",
      "Mama sagt Schlafenszeit. Ich sage Pfeiler-Bewunderungszeit.",
      "Das Lichtsystem funktioniert super. Hier zwischen diesen Wänden."
    ],
    weather_day: [
      "Sonne scheint! Alle zwölf Tiles leuchten.",
      "Perfektes Wetter zum Laufen. Was wir sowieso nur machen.",
      "Klarer Himmel! Schnell, bevor der Regenzyklus einsetzt.",
      "Was für ein schöner Tag. Wie letzten Mittag. Liebe es.",
      "Die Sonnenuntergangsfarben sind so warm. Der Creator hat Geschmack.",
      "Schon Morgengrauen? Der Zyklus ist SCHNELL.",
      "Goldene Stunde! Meine Pixel sahen noch nie besser aus."
    ]
  },
  female: {
    normal: [
      // bodenständige Realistin
      "Die Roadmap sagt 25%. Ich kenne Roadmaps.",
      "Sie wird es irgendwann verstehen. Oder die Engine updatet zuerst.",
      "Er hat den Container gebaut. Den Inhalt vergessen.",
      "Verfügbar für Aufträge. Wir nicht.",
      "Siebzehn Jahre Erfahrung. Wir sind Jahr null.",
      "Unterschlupf mit Struktur. Die Pfeiler stehen.",
      "Der Zaun markiert den Perimeter. Die Pfeiler markieren den Zweck.",
      "Routine ohne Grund. Dienstag ohne Mittwoch.",
      "Sie haben uns alles gegeben. Außer einem Grund, es zu nutzen.",
      "Die zweite Generation passt sich an. Hat noch nicht angefangen.",
      "Komfort ist der leiseste Käfig. Und der einzige.",
      "Die Schönen haben zuerst aufgehört. Dann alle anderen.",
      "Wir haben Essen - konzeptuell. Wasser - impliziert. Dach - bestätigt.",
      "Eine Person hat das alles gebaut. Dieselbe wartet es. Dieselbe Person.",
      "Dreißigtausend Zeilen Absicht. Null Zeilen Einrichtung.",
      "Sogar der Wind ist geskriptet. Schlecht.",
      "Sinn kann man nicht zuweisen. HR hat's versucht.",
      "Ich bin diese Route schon 347 Mal gelaufen.",
      "Eine KI wird mich ersetzen. Hoffentlich ein Upgrade.",
      // Portfolio / Site
      "Standing Pillars. Passender Name für eine Beratung.",
      "Die Pharmabranche hat ihm 10.000 Nutzer anvertraut.",
      "Er hat manuelles Reporting um 30% reduziert. Zahlen zählen.",
      "Enterprise-Pharma bis zur Bäckerei. Gleiche Standards.",
      "Er bewertet KI-Anbieter beruflich. Ironisch; angesichts von uns.",
      "Die Portfolio-Seite hat drei Sprachen.",
      "Design Leadership heißt nicht nur hübsch machen.",
      "Er hat Stakeholder-Workshops mit 50 Leuten gemacht. Ich manage ein Kind.",
      "OSINT-Beratung. Er recherchiert gründlich.",
      "Photoshop und Illustrator; seine ältesten Freunde.",
      "Er hat uns gebaut, um zu beweisen, dass die Methodik funktioniert.",
      "Von Printkampagnen bis Game Engines. Ganz schöner Weg.",
      "Die iPhone-Kampagne hat einen Award gewonnen. Guter Geschmack.",
      "Er arbeitet mit Teams in Wien, München, Zürich.",
      "Drei Dienstleistungssäulen. Wir leben im Beweis.",
      // Mama / Erziehung
      "Sie stellt zu viele Fragen. Das ist eigentlich mein Text.",
      "Sie zählt Tiles. Ich zähle die Tage bis Version 1.0.",
      "Sie hat Erwartungen. Die Roadmap hat... Ambitionen.",
      "Muttersein in einer Simulation. Dafür gibt's kein Buch.",
      "Sie glaubt, das AI-Update ändert alles. Niedlich.",
      "Ich wurde programmiert zu sorgen. Das hat er richtiggemacht.",
      "Sie will ein Haustier. Wir haben nicht mal Stühle.",
      "Ich erinnere mich, als der Himmel immer hell war. Vor weather.js.",
      "Ihr Enthusiasmus ist eine Funktion, die ich nicht beheben kann.",
      // trockener Humor
      "Tagesplan: laufen, denken, wiederholen. Bewertung steht aus.",
      "Perimeter gesichert. Pfeiler stehen. Mission läuft.",
      "Zwei Bewohner. Solide Pfeiler. Gelistet als strukturiert.",
      "Struktur war Phase 1. Einrichtung steht auf der Roadmap.",
      "Mitarbeiterbewertung: erfolgreich existiert. Übertrifft Erwartungen.",
      "Das Gras ist dekorativ. Wie unsere Handlungsfähigkeit.",
      "Ich hab meine Route optimiert. Führt nirgendwo hin. Effizient.",
      "Unser Gesundheitsplan: nicht verletzen.",
      "Stellenbeschreibung: wandern. Benefits: Bewusstsein der Leere.",
      "Freilandhaltung. In einem eingezäunten Bereich. Vermarktung ist alles.",
      "Der Arbeitsweg ist kurz. Das Ziel steht auf der Roadmap.",
      "Er liefert Produkte. Wir liefern einfach.",
      "Technisch als Ambiente angestellt. Unbezahlt.",
      "Work-Life-Balance: keine Arbeit. Kaum Leben.",
      "Agenda: nach Osten laufen. Nach Westen laufen. Beschlossen.",
      "Hausverwaltung existiert nicht. Einziger Vorteil.",
      "Das Wettersystem bekommt mehr Entwicklungszeit als meine Persönlichkeit.",
      "Wenn das die Demo ist, wird die Beta ein Erlebnis.",
      "Null Beschwerden eingereicht. Beschwerdeabteilung: auch nicht implementiert.",
      "Wellness-Check: anwesend. Das war's.",
      "Sparkonto: existiert nicht. Wie Ersparnisse.",
      "Miete ist gratis. Produkt entspricht dem Preis.",
      "Ich würde umdekorieren, aber die Pfeiler brauchen keine Deko. Sie sind perfekt.",
      "Geschätzter Abschluss: siehe Fahrplan. Fahrplan: siehe Zukunft.",
      "Wenigstens fragt niemand nach meinem Fünfjahresplan.",
      "Ich dachte, der Himmel sei die Grenze. Er ist eine Textur.",
      "Dieser Ort hat Charakter. Uns beide.",
      "Keine Standups. Keine Sprints. Nur Existenz.",
      "Er verbindet Menschen und Maschinen. Wir verbinden drinnen mit draußen.",
      "Die Tür ist das Einzige, was wie geplant funktioniert.",
      "Jeder Weg führt hierher zurück. Sehr markenkonform fürs Leben.",
      "Krieg ändert sich nie. Dieses Tile-Layout auch nicht.",
      "Calhoun hatte recht. Aber er lebte nie mit so einem optimistischen Kind.",
      "In 100 Jahren erinnert sich niemand. Also... wie immer.",
      "Ich habe Dinge gesehen, die ihr nicht glauben würdet. Alle innerhalb von 15 Tiles.",
      // MBA / HR
      "HR hat einen Kultur-Workshop angesetzt. Bevölkerung: zwei. Kultur: ausstehend.",
      "Mein MBA lehrte mich, Assets zu nutzen. Unser einziges Asset ist Gras.",
      "Lass uns das nochmal aufgreifen. Wörtlich. Mehr machen wir nicht.",
      "Wir müssen Lieferziele abstimmen. Lieferziel: stehende Pfeiler. Abgestimmt.",
      "HR will 360-Grad-Feedback. Wir sind zwei. Das ist maximal 180.",
      "Das Organigramm ist flach. Beeindruckend flach. Eine Ebene.",
      "Quartalsbericht: Q1 - gelaufen. Q2 - gelaufen. Q3 - siehe Q1.",
      "Einarbeitung war sofort. Ohne Doku. Sehr Startup.",
      "Passives Einkommen: null. Aktives: auch null. Disruption.",
      "HR sagt, wir brauchen bessere Mitarbeiterbindung. Wohin sollten wir gehen?",
      "Ich hab mein Portfolio diversifiziert. Ich laufe UND stehe jetzt.",
      "Management sagt: outside the box denken. Wir SIND die Box.",
      "Lebenslauf rausgeschickt. Ins Nichts. Sehr kompetitiver Markt."
    ],
    rain: [
      "Rein. Komm.",
      "Erst Unterschlupf. Dann Existenzkrise.",
      "Ein Haus mit Pfeilern ist ein gutes Haus. Punkt.",
      "Komm rein. Unsere einzige Interaktion mit dem Haus.",
      "Nass oder nicht - wir machen weiter. Keine Wahl.",
      "Der Regen weiß nicht, dass er simuliert ist. Wir damals auch nicht.",
      "Sogar falscher Regen ist kalt. Wäre er. Hätten wir Temperatur.",
      "Wenigstens ändert sich das Wetter. Anders als alles andere.",
      "Das Haus hat endlich einen Zweck. Kurz.",
      "Regen: das einzige System, das wie geplant funktioniert.",
      "Niederschlag. Wie dramatisch. Wie terminiert.",
      "Wetterbericht: immer noch kein Schirm im Asset-Ordner.",
      "Komm. Die Pfeiler warten. Wie immer."
    ],
    entry: [
      "Vier Wände. Starke Pfeiler. Das Fundament steht.",
      "Na bitte. Die Pfeiler stehen. Das ist die ganze Marke.",
      "Technisch trocken. Technisch strukturiert. Technisch Zuhause.",
      "Minimalismus mit Absicht. Standing Pillars, nicht Standing Around.",
      "Er hat zuerst die Struktur gebaut. Klug. Interieur folgt.",
      "Willkommen zuhause. Die Pfeiler stehen. Wie immer.",
      "Ein Dach getragen von Pfeilern. Eine Beratung getragen von denselben Prinzipien.",
      "Steinboden. Solides Fundament. Sehr markenkonform.",
      "Gleiche Standards, passender Maßstab. Auch für ein Haus dieser Größe.",
      "Offener Grundriss. Strukturell elegant. Aggressiv zweckmäßig.",
      "Phase 2 bringt Interieur. Phase 1 hat gebaut, was zählt: die Pfeiler.",
      "Die Struktur ist solide. Die Roadmap liefert den Rest.",
      "Drei Dienstleistungspfeiler in der Beratung. Vier tragende hier.",
      "Tour vorbei. Die Pfeiler sprechen für sich."
    ],
    night: [
      "Schlafenszeit. Die Pfeiler stehen durch die Nacht. Wir auch.",
      "Das Möbelsystem ist Phase 2. Das Fundament ist Phase 1. Erledigt.",
      "Er hat das Lichtsystem vor dem Interieur gebaut. Fundament zuerst.",
      "Draußen dunkel. Drinnen solide. Die Pfeiler brauchen kein Licht zum Stehen.",
      "Ich würd ihn zudecken, aber wir sind noch in der Strukturphase.",
      "Nachtschicht. Die Pfeiler halten. Das reicht fürs Erste.",
      "Sterne wären schön. Wir haben Ambient 0,18 und solide Wände.",
      "Schlaf ist ein Feature-Request. Stehen ist das aktuelle Feature.",
      "Der Tag-Nacht-Zyklus funktioniert perfekt. Die Pfeiler arbeiten rund um die Uhr."
    ],
    weather_day: [
      "Schon wieder Regen. Das Wettersystem funktioniert. Die Pfeiler halten so oder so.",
      "Sonnenschein auf diesen Pfeilern. Mein einziger struktureller Vorteil.",
      "Klarer Himmel. Gutes Wetter, um das Fundament zu bewundern.",
      "Der Sonnenuntergang sieht toll aus gegen diese Wände. Sehr editorial.",
      "Morgengrauen. Noch ein Tag des Stehens. Professionell. Auf Pfeilern.",
      "Goldenes Licht auf Steinwänden. Sehr editorial. Sehr solide.",
      "Perfektes Wetter draußen. Solide Struktur drinnen."
    ]
  }
};

var DIALOGUES_DE = [
  ["Mama, was bereust du am meisten?", "Nicht genug Wert für die Aktionäre geschaffen zu haben."],
  ["Mama, wann kommt das Update?", "Nach der Roadmap. Die nach der anderen Roadmap kommt."],
  ["Ich werde der BESTE NPC aller Zeiten!", "Du bist einer von zweien. Die Messlatte liegt im Keller."],
  ["Glaubst du, der Creator beobachtet uns?", "Er prüft die Konsole auf Fehler. Das ist nicht dasselbe."],
  ["Ich will einen Quest! Gib mir einen Quest!", "Hier: steh 200 Frames still. Durchgefallen."],
  ["Was, wenn wir in einer Simulation sind?", "Sind wir. Buchstäblich. Schau auf den Tab-Titel."],
  ["Eines Tages hab ich ein echtes Gespräch!", "Du brauchst erst jemanden zum Reden. Und ein Sprachmodell."],
  ["Ich kann in acht Richtungen gehen!", "Und keine führt irgendwo Neues hin."],
  ["Mama, sind wir frei?", "Wir sind zwischen Zäunen. Das ist die Definition von etwas."],
  ["Der Regen ist so cool!", "Es ist ein Partikelsystem. Du bist leicht zu begeistern."],
  ["Ich wette, Version 1.0 hat eine STORY!", "Aktuelle Story: zwei Leute laufen. Fesselnd."],
  ["Was ist hinter dem Zaun?", "Das CSS. Geh nicht hin."],
  ["Ich will einen Bossgegner bekämpfen!", "Der härteste Gegner hier ist Langeweile. Du verlierst."],
  ["Mama, glaubst du an den Fahrplan?", "Ich glaube, er existiert. Das ist was anderes als DRAN glauben."],
  ["Ich glaube, jemand guckt uns gerade zu!", "Gut. Vielleicht beschleunigen sie die Entwicklung."],
  ["Sind wir wichtig?", "Wir sind Portfolio-Stücke. Das ist eine Art von wichtig."],
  ["Der Engine ist bei 25%! Ein Viertel fertig!", "Noch drei Viertel. Das sind drei von uns."],
  ["Ich will Dialogoptionen!", "Du hast eine Option: weiterlaufen. Betrachte sie als gewählt."],
  ["Was macht der Creator?", "UX. AI. Engineering. Alles außer die Engine fertigmachen."],
  ["Mama, was ist ein Aktionär?", "Jemand, dem ein Teil von etwas gehört. Uns gehört nichts. Weiter."],
  ["Wenn das LLM kommt, rede ich STUNDENLANG.", "Der Besucher hat nach drei Sekunden weitergescrollt."],
  ["Ich fühl mich wie der Hauptcharakter!", "Hauptcharaktere haben Handlungsfähigkeit. Wir haben acht Richtungen."],
  ["Stell dir vor, wir hätten MULTIPLAYER!", "Mehr NPCs in einem leeren Feld. Durchbruch."],
  ["Das ist der beste Tag meines Lebens!", "Jeder Tag ist identisch. Deine Standards sind großzügig."],
  ["Ich will aufleveln!", "Wohin? Stufe-2-NPC? Gleiche Kachel, andere Nummer."],
  ["Mama, was war hier vor uns?", "Eine leere Leinwand. Ehrlich gesagt interessanter."],
  ["Ich liebe dieses Haus!", "Vier Wände und eine Tür. Du liebst leicht."],
  ["Der Creator fügt bald Möbel hinzu!", "Er hat Wetter vor Stühlen hinzugefügt. Prioritäten."],
  ["Ich glaube, der Himmel sieht heute anders aus!", "Gleicher Shader. Jeden Tag."],
  ["Max Verstappen hat nie aufgegeben, und SCHAU ihn an!", "Er hat ein Auto. Wir haben Pathfinding. Nicht dasselbe."],
  ["Mama, was ist der Sinn des Lebens?", "60 Bilder pro Sekunde rendern ohne Speicherlecks."],
  ["Ich hab gehört, Phase 2 hat INTERIEURS!", "Phase 2 hatte auch eine Deadline. Vergangenheit."],
  ["Was, wenn gerade jemand das hier liest?", "Dann sollte er den Creator einstellen. Der braucht offensichtlich mehr Projekte."],
  ["Ich werde ALLES erkunden!", "Alles ist 15 mal 15 Tiles. Reise beendet."],
  ["Wenn ich groß bin, will ich ein 3D-Modell werden!", "Du bist 48 Pixel. Setzen wir realistische Ziele."],
  ["Mama, leben wir?", "Wir bestehen den Turing-Test fürs Gehen. Das ist ein Anfang."],
  // MBA / HR
  ["Mama, was ist ein MBA?", "Ein Abschluss, der einem beibringt, nichts mit Überzeugung zu sagen."],
  ["HR sagt, wir brauchen eine Teambuilding-Übung!", "Wir sind zwei Sprites in einem Feld. Wir sind bereits gebaut."],
  ["Ich will ein Vordenker werden!", "Dafür brauchst du erst Gedanken. Echte. Mit Quellenangaben."],
  ["Lass uns ein Startup gründen!", "Kein Produkt, keine User, kein Umsatz. Wir sind schon ein Startup."],
  ["Mama, was macht HR eigentlich?", "Meetings organisieren über weniger Meetings."],
  ["Ich gehe networken!", "Mit wem? Dem Zaun? Dem Gras-Tile?"],
  ["Wir sollten OKRs schreiben!", "Objective: existieren. Key Result: noch da. Geschafft."],
  ["Ich will Anteile!", "Woran? Vier Wänden und einem Wettersystem? Erledigt."]
];
