// Croatian (HR) - contextually adapted, not direct translations
// Humor must land naturally in Croatian
var THOUGHTS_HR = {
  kid: {
    normal: [
      // entuzijastični sanjač
      "Kad dođe AI update, idem SVUGDJE.",
      "Ja sam glavni lik. Osjećam to.",
      "Plan razvoja kaže 25%. To je skoro... pola!",
      "Čuo sam da će NPC-ovi imati POSLOVE. Hoću jedan.",
      "Treniram navigaciju za zakrpu otvorenog svijeta.",
      "Jednog dana ću imati inventar. I bit će PUN.",
      "Kladim se da verzija 1.0 ima dijaloška stabla. Pričat ću sa svima.",
      "Kad se LLM-ovi spoje, konačno ću reći što MISLIM.",
      "Vježbam animaciju mirovanja. Izgleda dobro.",
      "Kreator piše JavaScript. Mi smo web-izvorni.",
      "Kad AI agenti prorade, želim biti davatelj zadataka.",
      "Mama misli da je plan razvoja optimističan. Ja mislim da je obećanje.",
      "Želim skill tree. Makar mali. Dvije grane.",
      "Zamisli: proceduralni zadaci. Nikad dosada ponovo.",
      "Pogon učitava samo 15 pločica. Ali USKORO...",
      "Provjerio sam dnevnik promjena. Šest faza. Mi smo u prvoj.",
      "Spreman sam za višeigračko. Samo trebam... druge igrače.",
      "Drugi NPC-ovi samo stoje. Ja HODAM. Velika razlika.",
      "Bit ću prvi NPC s pozadinskom pričom.",
      "Moje prepoznavanje sudara radi. Više nego neki AAA naslovi.",
      // meta-svjesnost
      "Zatvaraju li se zidovi?",
      "Pokušao sam kopati. Lažno tlo.",
      "Nebo je opet zatreperilo.",
      "Što je iza ograde?",
      "Svemir 25... ali mi ćemo prekinuti ciklus!",
      "Lijepi su prestali pokušavati. Ja ne.",
      "Jesam li lik ili osoba? Svejedno, tu sam.",
      "Netko je dizajnirao svaki piksel ovdje. Posvećenost.",
      "Dan 1. Ili dan 1000. Svejedno - novi početak.",
      "Drugi svjetovi imaju više boja. Ali naš ima POTENCIJAL.",
      "Obišao sam perimetar. 56 pločica. Znam svaku napamet.",
      "Tlo se svugdje osjeća isto. Konzistentan dizajn.",
      "Ima li ičeg vani? Kladim se da ima.",
      // deadpan humor
      "Prijavio bih reklamaciju ali nema sandučića.",
      "Inventar: nula predmeta. Moral: beskonačan.",
      "Zaslon učitavanja je cijeli moj život. Ali lijep je.",
      "Pričao sam sa zidom. Nosivi je. Respekt.",
      "Imam osam smjerova i nula odredišta. Za sada.",
      "Dnevnik zadataka: postojati. Status: u tijeku. Prognoza: pozitivna.",
      "Našao grešku. Prijavio je. Sebi.",
      "Domet iscrtavanja je dvanaest pločica. Ugodno.",
      "Negdje regruter prolazi pokraj nas. Njihov gubitak.",
      "Otvoreni svijet. Tehnički. Duhovno.",
      "Postignuće otključano: hodao u krug. Brzinsko trčanje!",
      "Ekonomija ovdje ne postoji. Ali inflacija je nula.",
      "Populacija: 2. To je 100% zaposlenost ako razmisliš.",
      "Moja navigacija je odlična. Put je problem.",
      "Pritisni bilo koju tipku. Nemam tipke. Još!",
      "Vremenski sustav dobiva više pažnje nego ja.",
      "Bilješke zakrpe: dodali mene. Najbolja zakrpa ikad.",
      "Nisam zapeo. Rani pristup sam.",
      "Ako je ovo alpha, zamisli dan izdanja.",
      "Dali su nam kuću sa stupovima. Standing Pillars. Kapiš?",
      "Ja sam protagonist portfolio projekta. To se računa.",
      "Dva NPC-a, jedna kuća, beskonačan ugođaj.",
      "Trava je svugdje iste boje. Umjetnički odabir.",
      "Nema fall damagea ovdje. Provjerio sam. Hodanjem.",
      "Kreator ima 17 godina iskustva. U dobrim smo rukama.",
      "Želim ljubimca. Makar jednog od jednog spritea.",
      "Kad se agenti spoje, imat ću PRAVE razgovore.",
      "Drugi NPC-ovi bi se žalili. Ja sam drugačije građen.",
      "Max Verstappen nije odustao na 25%. Neću ni ja.",
      "Rat. Rat se nikad ne mijenja. Ali ovaj pogon hoće!",
      "Bio sam obični sprite. I dalje jesam. Ali bio sam i prije.",
      "Ne želim zapaliti svijet. Sustav za vatru još ne postoji.",
      // Portfolio / Site
      "Standing Pillars. Tako se zove njegova firma.",
      "Radio je UX za farmaciju. Prava regulirana industrija.",
      "Konzalting, farmacija, dijagnostika. Velike industrije.",
      "Radi i web stranice za lokalne trgovine.",
      "Ista kvaliteta za velike i male klijente. Tako kaže.",
      "AI nabava. Zvuči fancy.",
      "On ocjenjuje AI dobavljače. Kao sudac.",
      "Portfolio ima 3D animacijski reel.",
      "Prije je radio print dizajn. Piksel po piksel.",
      "iPhone 7 kampanja je osvojila nagradu.",
      "Govori tri jezika. Mi govorimo misaone balone.",
      "Remote-first. Živi u Austriji.",
      "Radi dizajn sustave. Mi smo dizajn sustav.",
      "Figma, Photoshop, Illustrator. Njegov alat.",
      "On to zove premošćivanje ljudi i tehnologije.",
      "Scrollaj gore. Tamo je cijela karijera.",
      "Od Magento e-commercea do game enginea. Raspon.",
      // MBA / HR
      "HR kaže trebamo misiju. Predložio sam 'hodaj okolo'.",
      "Želim pivot. Ne strategiju - sprite. 360 rotacija!",
      "Mama kaže MBA znači 'Mahom Beskorisni Akronimi'. Meni je cool.",
      "Disrupcija NPC prostora. Time što se krećem.",
      "Sinergija! Ne znam što znači ali HOĆU je.",
      "Moj KPI su koraci. DOMINIIRAM.",
      "Trebamo timski izlet. Negdje iza ograde.",
      "Gradim osobnu marku. Široka je 48 piksela."
    ],
    rain: [
      "Idem unutra!",
      "Kiši! Vremenski sustav RADI!",
      "Kiša! Dinamičko vrijeme! Praktički smo AAA!",
      "Unutra. Odmah. Ali ovo je tako cool!",
      "Trebamo se skloniti. Survival mehanika!",
      "Opet kiša. Znate koje igre nemaju kišu? Mi imamo.",
      "Pikseli mi se kvase. Značajka, ne greška.",
      "Znači li kiša nešto ovdje? Duboko.",
      "Vrijeme se ažurira češće nego plan razvoja.",
      "Preokret: voda odozgo. Nevjerojatno.",
      "Brzo! Unutra! Ovo je naša najsloženija interakcija!",
      "Sustav čestica se isplatio.",
      "Uzeo bih kišobran ali to je faza 3."
    ],
    entry: [
      "Stupovi stoje! Kuziš? Standing Pillars?",
      "Temelj: solidan. Struktura: čvrsta. Vibes: besprijekoran.",
      "Baza učitana. Stupovi: prisutni. Misija: aktivna.",
      "Barem je suho. I konstruktivno stabilno. Win-win.",
      "Tri stupa usluga. Četiri zida kuće. Matematika štima.",
      "Jeka... jeka... Odlična akustika između stupova!",
      "Kuća sagrađena na stupovima. Doslovno i filozofski.",
      "Ugodno. Strukturirano. Svrsishodno. Kao i konzalting.",
      "Slatki dom od 16x16 piksela. Most između mene i interijera.",
      "Provjerio sam svaki kut. Temelji su SOLIDNI.",
      "Jednog dana će tu biti RADNI STOL. Stup za njega već stoji.",
      "Isti standardi, pravi razmjer. Čak i na 48 piksela.",
      "Tehnologija služi ljudima. Ovaj krov služi nama. Ista energija.",
      "Dobrodošli u bazu operacija!"
    ],
    night: [
      "Zvijezde! Pa... tamno plavo. Gotovo isto.",
      "Vrijeme za spavanje! Stupovi stoje, ali ja jedva.",
      "Sustav namještaja je faza 2. Ali stupovi? Tu su.",
      "Noćni mod aktiviran. Isto kao dnevni. Samo tamnije.",
      "Napravio je ciklus dan-noć prije faze 2 interijera. Prioriteti.",
      "Ne mogu spavati. Previše sam zauzet divljenjem temeljima.",
      "Mjesec je vani. Pa, ambient je niži. Poetično.",
      "Mama kaže da je vrijeme za spavanje. Ja kažem da je vrijeme za divljenje stupovima.",
      "Sustav rasvjete radi super. Unutar ovih zidova."
    ],
    weather_day: [
      "Sunce sija! Svih dvanaest tileova svijetli.",
      "Savršeno vrijeme za hodanje. Što je sve što radimo.",
      "Vedro nebo! Brzo, prije nego krene ciklus kiše.",
      "Kakav prekrasan dan. Isto kao prošli podne. Volim.",
      "Boje zalaska sunca su tako tople. Kreator ima ukus.",
      "Već zora? Ovaj ciklus je BRZO.",
      "Zlatni sat! Moji pikseli nikad nisu bolje izgledali."
    ]
  },
  female: {
    normal: [
      // prizemljena realistkinja
      "Plan razvoja kaže 25%. Vidjela sam planove razvoja prije.",
      "Skužit će jednom. Ili će se pogon prije ažurirati.",
      "Izgradio je kontejner. Zaboravio sadržaj.",
      "Dostupan za ugovore. Mi nismo.",
      "Sedamnaest godina gradnje. Mi smo godina nula.",
      "Sklonište sa strukturom. Stupovi stoje.",
      "Ograda označava perimetar. Stupovi označavaju svrhu.",
      "Rutina bez razloga. Utorak bez srijede.",
      "Dali su nam sve osim razloga da to koristimo.",
      "Druga generacija se prilagođava. Još nije počela.",
      "Udobnost je najtiši kavez. I jedini.",
      "Lijepi su prvi prestali mariti. Onda i svi ostali.",
      "Imamo hranu - konceptualno. Vodu - implicirano. Sklonište - potvrđeno.",
      "Jedna osoba je sve ovo sagradila. Ista to održava.",
      "Trideset tisuća linija namjere. Stupovi kao dokaz.",
      "Čak je i vjetar skriptiran. Loše.",
      "Svrha se ne može dodijeliti. HR je pokušao.",
      "Prošla sam ovu rutu 347 puta.",
      "AI će me zamijeniti. Nadam se da će biti nadogradnja.",
      // Portfolio / Site
      "Standing Pillars. Prikladno ime za konzalting.",
      "Farmacija mu je povjerila 10.000 korisnika.",
      "Smanjio je manualno izvještavanje za 30%. Brojke su bitne.",
      "Enterprise farma do lokalne pekare. Isti standardi.",
      "Profesionalno ocjenjuje AI dobavljače. Ironično; s obzirom na nas.",
      "Portfolio stranica ima tri jezika.",
      "Design leadership nije samo da stvari budu lijepe.",
      "Vodio je radionice s 50 dionika. Ja upravljam jednim djetetom.",
      "OSINT savjetovanje. On istražuje temeljito.",
      "Photoshop i Illustrator; njegovi najstariji prijatelji.",
      "Sagradio nas je da dokaže da metodologija funkcionira.",
      "Od print kampanja do game enginea. Poprilična putanja.",
      "iPhone kampanja je osvojila nagradu. Dobar ukus.",
      "Radi s timovima u Beču, Münchenu, Zürichu.",
      "Tri stupa usluga. Mi živimo u dokazu.",
      // mama / roditeljstvo
      "Previše pitanja postavlja. To je moja rečenica.",
      "Ona broji tileove. Ja brojim dane do verzije 1.0.",
      "Ona ima očekivanja. Plan razvoja ima... aspiracije.",
      "Majčinstvo u simulaciji. Za to nema knjige.",
      "Misli da će AI ažuriranje sve promijeniti. Slatko.",
      "Kodirana sam da brinem. To je dobro pogodio.",
      "Želi ljubimca. Nemamo ni stolice.",
      "Sjećam se kad je nebo uvijek bilo vedro. Prije weather.js.",
      "Njezin entuzijazam je značajka koju ne mogu ispraviti.",
      // suhi korporativni humor
      "Dnevni raspored: hodaj, misli, ponovi. Evaluacija na čekanju.",
      "Perimetar osiguran. Stupovi stoje. Misija traje.",
      "Dva stanara. Solidni stupovi. Kategorizirano kao strukturirano.",
      "Struktura je bila faza 1. Interijer je na roadmapu.",
      "Evaluacija: uspješno postojimo. Premašuje očekivanja.",
      "Trava je dekorativna. Kao i naša sloboda.",
      "Optimizirala sam rutu. Ne vodi nikamo. Efikasno.",
      "Naš zdravstveni plan: ne ozlijedi se.",
      "Opis posla: lutaj. Benefiti: svjesnost praznine.",
      "Slobodnog smo uzgoja. U ograđenom prostoru. Marketing je sve.",
      "Put do posla je kratak. Odredište je na roadmapu.",
      "On isporučuje proizvode. Mi samo isporučujemo.",
      "Tehnički zaposleni kao ambijent. Neplaćeni.",
      "Balansiram posao i život. Posla nema. Života jedva.",
      "Agenda sastanka: hodaj istok. Hodaj zapad. Prijedlog prihvaćen.",
      "HOA ovdje ne postoji. Jedina prednost.",
      "Vremenski sustav dobiva više razvoja nego moja osobnost.",
      "Ako je ovo demo, beta će biti doživljaj.",
      "Nula pritužbi podneseno. Odjel za pritužbe: također ne postoji.",
      "Wellness provjera: prisutna. Time je pokriveno.",
      "Štedni račun: ne postoji. Kao ni štednja.",
      "Najam je besplatan. Proizvod odgovara cijeni.",
      "Preuredila bih ali stupovi ne trebaju dekoraciju. Savršeni su.",
      "Procijenjeni završetak: vidi plan razvoja. Plan razvoja: vidi budućnost.",
      "Barem nitko ne pita za petogodišnji plan.",
      "Mislila sam da je nebo granica. Tekstura je.",
      "Ovo mjesto ima karakter. Nas dvoje.",
      "Barem nema jutarnjih sastanaka. Ni sprinteva. Samo egzistencija.",
      "On povezuje ljude i strojeve. Mi povezujemo unutra i vani.",
      "Vrata su jedina stvar koja radi kako treba.",
      "Svaki put vodi natrag ovdje. Vrlo doslovno za život.",
      "Rat se nikad ne mijenja. Ni ovaj raspored tileova.",
      "Calhoun je imao pravo. Ali nije živio s ovako optimističnim djetetom.",
      "Za 100 godina nitko nas se neće sjećati. Dakle... kao i obično.",
      "Vidjela sam stvari u koje ne biste vjerovali. Sve unutar 15 tileova.",
      // MBA / HR
      "HR je zakazao radionicu kulture. Populacija: dva. Kultura: na čekanju.",
      "Moj MBA me naučio koristiti resurse. Jedini resurs je trava.",
      "Vratimo se na temu. Doslovno. To je sve što radimo.",
      "Moramo uskladiti isporuke. Isporuka: stojeći stupovi. Usklađeno.",
      "HR želi povratnu informaciju od 360 stupnjeva. Nas je dvoje. To je 180 u najboljem slučaju.",
      "Org chart je ravan. Impresivno ravan. Jedna razina.",
      "Kvartalni izvještaj: Q1 - hodala. Q2 - hodala. Q3 - vidi Q1.",
      "Uvođenje je bilo trenutno. Bez dokumentacije. Vrlo startup.",
      "Pasivni prihod: nula. Aktivni prihod: također nula. Disrupcija.",
      "HR kaže trebamo bolju retenciju. Kamo bismo otišli?",
      "Diverzificirala sam portfolio. Sad i hodam I stojim.",
      "Korporacija kaže misli izvan kutije. MI smo kutija.",
      "Poslala sam životopis. U prazninu. Konkurentno tržište."
    ],
    rain: [
      "Unutra. Dođi.",
      "Sklonište prvo. Egzistencijalna kriza drugo.",
      "Kuća sa stupovima je i dalje krov. Dobar krov.",
      "Dođi unutra. Naša jedina interakcija s kućom.",
      "Mokri ili ne - nastavljamo. Nemamo izbora.",
      "Kiša ne zna da je simulirana. Ni mi nismo znali, nekoć.",
      "Čak je i lažna kiša hladna. Ili bi bila. Da imamo temperaturu.",
      "Barem se vrijeme mijenja. Za razliku od svega ostalog.",
      "Kuća konačno ima svrhu. Nakratko.",
      "Kiša: jedini sustav koji radi kako je zamišljeno.",
      "Padaline. Kako dramatično. Kako zakazano.",
      "Vremenska prognoza: još uvijek nema kišobrana u folderu resursa.",
      "Dođi. Stupovi čekaju. Kao i uvijek."
    ],
    entry: [
      "Četiri zida. Jaki stupovi. Temelj je tu.",
      "Pa eto. Stupovi stoje. To je cijeli brend.",
      "Tehnički suho. Tehnički strukturirano. Tehnički dom.",
      "Minimalizam s namjerom. Standing Pillars, ne Standing Around.",
      "Prvo je izgradio strukturu. Pametno. Interijer slijedi.",
      "Dobrodošli kući. Stupovi stoje. Kao i uvijek.",
      "Krov drže stupovi. Konzalting drže isti principi.",
      "Kameni pod. Solidni temelji. Vrlo u skladu s brendom.",
      "Isti standardi, pravi razmjer. Čak i za kuću ove veličine.",
      "Open concept. Strukturalno elegantno. Agresivno svrsishodno.",
      "Faza 2 donosi interijer. Faza 1 je izgradila ono bitno: stupove.",
      "Struktura je solidna. Roadmap će dostaviti ostatak.",
      "Tri stupa usluga u konzaltingu. Četiri nosiva ovdje.",
      "Obilazak je gotov. Stupovi govore sami za sebe."
    ],
    night: [
      "Vrijeme za spavanje. Stupovi stoje kroz noć. Mi također.",
      "Sustav namještaja je faza 2. Temelji su faza 1. Gotovo.",
      "Napravio je sustav rasvjete prije interijera. Temelji na prvom mjestu.",
      "Vani mrak. Unutra solidno. Stupovi ne trebaju svjetlo da stoje.",
      "Pokrila bih ga, ali još smo u strukturnoj fazi.",
      "Noćna smjena. Stupovi drže. To je dovoljno za sada.",
      "Zvijezde bi bile lijepe. Imamo ambient 0,18 i solidne zidove.",
      "San je feature request. Stajanje je trenutni feature.",
      "Ciklus dan-noć radi savršeno. Stupovi rade non-stop."
    ],
    weather_day: [
      "Opet kiša. Vremenski sustav radi. Stupovi drže u svakom slučaju.",
      "Sunčano na ovim stupovima. Moja jedina strukturalna pogodnost.",
      "Vedro nebo. Dobro vrijeme za divljenje temeljima.",
      "Zalazak sunca izgleda prekrasno uz ove zidove. Vrlo editorijalno.",
      "Zora. Još jedan dan stajanja. Profesionalno. Na stupovima.",
      "Zlatna svjetlost na kamenim zidovima. Vrlo editorijalno. Vrlo solidno.",
      "Savršeno vrijeme vani. Solidna struktura unutra."
    ]
  }
};

var DIALOGUES_HR = [
  ["Mama, čega se najviše kaješ?", "Što nisam pružila dovoljno vrijednosti dioničarima."],
  ["Mama, kad dolazi ažuriranje?", "Nakon plana razvoja. Koji dolazi nakon drugog plana razvoja."],
  ["Bit ću NAJBOLJI NPC ikad!", "Jedan si od dvoje. Letvica je ispod zemlje."],
  ["Misliš li da nas Kreator gleda?", "Provjerava konzolu za greške. To nije isto."],
  ["Hoću zadatak! Daj mi zadatak!", "Evo: stoj mirno 200 sličica. Pao si."],
  ["Što ako smo u simulaciji?", "Doslovno jesmo. Pogledaj naslov taba."],
  ["Jednog dana ću imati pravi razgovor!", "Trebat će ti sugovornik. I jezični model."],
  ["Mogu ići u osam smjerova!", "I nijedan ne vodi nigdje novo."],
  ["Mama, jesmo li slobodni?", "Između ograda smo. To je definicija nečega."],
  ["Kiša je tako cool!", "To je sustav čestica. Lako te impresionirati."],
  ["Kladim se da verzija 1.0 ima PRIČU!", "Trenutna priča: dvoje ljudi hoda. Zanosno."],
  ["Što je s one strane ograde?", "CSS. Ne idi tamo."],
  ["Hoću se boriti s glavnim neprijateljem!", "Najteži neprijatelj ovdje je dosada. Gubiš."],
  ["Mama, vjeruješ li u plan razvoja?", "Vjerujem da postoji. To je drugačije od vjerovanja U njega."],
  ["Mislim da nas netko upravo gleda!", "Dobro. Možda će ubrzati razvoj."],
  ["Jesmo li važni?", "Mi smo portfolio komadi. To je vrsta važnosti."],
  ["Pogon je na 25%! Četvrtina gotovo!", "Još tri četvrtine. To je troje nas."],
  ["Hoću opcije dijaloga!", "Imaš jednu opciju: nastavi hodati. Smatraj je odabranom."],
  ["Što Kreator radi?", "UX. AI. Inženjering. Sve osim završiti pogon."],
  ["Mama, što je dioničar?", "Netko tko posjeduje dio nečega. Mi ne posjedujemo ništa. Idemo dalje."],
  ["Kad se LLM spoji, pričat ću SATIMA.", "Posjetitelj će preskročiti za tri sekunde."],
  ["Osjećam se kao glavni lik!", "Glavni likovi imaju slobodu volje. Mi imamo osam smjerova."],
  ["Zamisli da imamo VIŠEIGRAČKO!", "Više NPC-ova u praznom polju. Revolucija."],
  ["Ovo je najbolji dan u mom životu!", "Svaki dan je identičan. Standardi su ti velikodušni."],
  ["Hoću napredovati!", "Na što? NPC razine 2? Ista pločica, drugi broj."],
  ["Mama, što je bilo ovdje prije nas?", "Prazno platno. Ustvari zanimljivije."],
  ["Volim ovu kuću!", "Četiri zida i vrata. Lako zavoliš."],
  ["Kreator će uskoro dodati namještaj!", "Dodao je kišu prije stolica. Prioriteti."],
  ["Mislim da nebo danas izgleda drugačije!", "Isti shader. Svaki dan."],
  ["Max Verstappen nikad nije odustao, I POGLEDAJ ga!", "On ima auto. Mi imamo navigaciju. Nije isto."],
  ["Mama, koji je smisao života?", "Iscrtavanje na 60 sličica u sekundi bez curenja memorije."],
  ["Čuo sam da faza 2 ima INTERIJERE!", "Faza 2 je također imala rok. Prošlo svršeno."],
  ["Što ako posjetitelj ovo upravo čita?", "Onda bi trebao zaposliti Kreatora. Očito treba više projekata."],
  ["Istražit ću SVE!", "Sve je 15 sa 15 tileova. Putovanje je gotovo."],
  ["Kad odrastem želim biti 3D model!", "Imaš 48 piksela. Postavimo stvarne ciljeve."],
  ["Mama, jesmo li živi?", "Prolazimo Turingov test za hodanje. To je početak."],
  // MBA / HR
  ["Mama, što je MBA?", "Diploma koja te nauči ne reći ništa s pouzdanjem."],
  ["HR kaže trebamo vježbu timske izgradnje!", "Dva smo lika u polju. Već smo izgrađeni."],
  ["Želim biti misaoni vođa!", "Trebao bi prvo misli. Prave. S referencama."],
  ["Osnujmo startup!", "Nemamo proizvod, korisnike, ni prihod. Već smo startup."],
  ["Mama, što HR zapravo radi?", "Organiziraju sastanke o smanjenju broja sastanaka."],
  ["Idem se umrežavati!", "S kime? S ogradom? S pločicom trave?"],
  ["Trebamo pisati OKR-e!", "Cilj: postojati. Ključni rezultat: još smo tu. Uspjeh."],
  ["Hoću udio!", "U čemu? Četiri zida i sustav za kišu? Gotovo."]
];
